package com.informedcitizen.data.zipcrosswalk

sealed interface ZipDistrictResult {
    data class Single(val state: String, val district: Int) : ZipDistrictResult
    data class Multiple(val state: String, val districts: List<Int>) : ZipDistrictResult
    data object Miss : ZipDistrictResult
}

interface ZipDistrictLookup {
    suspend fun lookup(zip: String): ZipDistrictResult

    /**
     * Returns true if the bundled ZIP -> congressional-district crosswalk asset
     * is present and parseable. The HUD-derived asset is generated by a manual
     * pipeline step and may be absent from a build, in which case the picker
     * UI should hide the ZIP entry path entirely instead of silently treating
     * every ZIP as a miss.
     */
    suspend fun isAvailable(): Boolean
}
